Task1: Initializing the working environment
vladislav-miroshnikov/formal-lang-course pull request #1
Opened 2021-09-05 16:37 UTC by vladislav-miroshnikov

- Added functions for working with graphs

- Added tests

- Console application implemented

- Added launch of tests to workflows

2021-09-05 17:47 UTC, vladislav-miroshnikov commented
Waiting for an ability to request review

2021-09-06 13:10 UTC, vdshk requested changes
Также есть пара глобальных замечаний.

* Запускаться `REPL` должен через `python -m project`. Сейчас так не работает.

* >   - [ ] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.

    Именно **по имени**. В наборе данных у графов есть имена. Такие как `geospecies`, `pizza`, `enzyme`. См. [Get a real graph](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph)
    
* Копируйте из `tasks` полностью описание задачи в комментарий вашего PR и проставляйте чекбоксики, пожалуйста. Так будет и вам и мне проще видеть, что требовалось сделать и что уже сделано.

* Не забудьте написать в `project/README.md` как запускать ваше **консольное приложение**.

* Убедитесь, что ваши тесты покрывают все возможные крайние случаи.
    
> Мой комментарий на русском языке, так как курс читается на русском языке.
Если вы согласны перейти на английский, напишите мне об этом, пожалуйста, в комментариях.

2021-09-06 13:10 UTC, vadyushkins commented on .github/workflows/tests.yml
> +        python-version: [ 3.8 ]
Добавьте в матрицу `ubuntu-latest`, `macos-latest`, `windows-latest`, чтобы тестировать ваше решение на всех платформах. Мы в задачах будем использовать только кросс-платформенные библиотеки, поэтому проблем не будет.

2021-09-06 13:10 UTC, vadyushkins commented on project/__init__.py
> -print("import sources directory")
Здесь должны быть импорты основных функций пакета.
Что-то вроде
```python
import project.console_app
from project.console_app import *
```
Заодно пропишите в подмодулях `__all__`

2021-09-06 13:10 UTC, vadyushkins commented on project/__main__.py
> +    init_console()
Запустил из корня репозитория `python3 -m project` и получил
```
ModuleNotFoundError: No module named 'console_app'
```
Кажется так не должно быть. Или я что-то сделал не так?

2021-09-06 13:10 UTC, vadyushkins commented on project/console_app.py
> +}
По заданию у вас должны быть следующие команды. (названия примерные)
"get_graph_info", "create_two_cycles_graph", "save_to_dot", "quit"

2021-09-06 13:10 UTC, vadyushkins commented on requirements.txt
> +networkx
`networkx` уже есть в зависимостях у `cfpq_data`. Почему вы его добавили?
```suggestion
```

2021-09-06 13:10 UTC, vadyushkins commented on project/console_app.py
> +def init_console():
Используйте [`NumPy docstrings`](https://numpydoc.readthedocs.io/en/latest/format.html).
Минимально требуется: `1. Short summary`, `4. Parameters`, `5. Returns` или `6. Yields`

2021-09-06 13:10 UTC, vadyushkins commented on project/console_app.py
> +def init_console():
И так для всех функций и классов.

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_graph_utils.py
> +path = "graph_sample.dot"
Зачем это вынесено в отдельную переменную?

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_graph_utils.py
> +    assert cfpq_data.get_labels(test_graph, verbose=False) == graph_info["labels"]
В unit тестах лучше придерживаться правила один assert на тест.

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_graph_utils.py
> +    assert True == (os.path.isfile(path) and os.path.getsize(path) > 0)
Порядок сравнения должен быть `assert actual == expected`

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_graph_utils.py
> +    assert True == (os.path.isfile(path) and os.path.getsize(path) > 0)
А где вы проверяете то, что вы сохранили файл и он сохранился правильно?

2021-09-08 12:23 UTC, vladislav-miroshnikov commented on project/console_app.py
> +def init_console():
Добавлено

2021-09-08 12:24 UTC, vladislav-miroshnikov commented on tests/test_graph_utils.py
> +path = "graph_sample.dot"
В тот момент использовалось в двух тестах, сейчас уже переделал

2021-09-08 12:24 UTC, vladislav-miroshnikov commented on tests/test_graph_utils.py
> +    assert cfpq_data.get_labels(test_graph, verbose=False) == graph_info["labels"]
Хорошо

2021-09-08 12:25 UTC, vladislav-miroshnikov commented on tests/test_graph_utils.py
> +    assert True == (os.path.isfile(path) and os.path.getsize(path) > 0)
Новый тест "test_creating_and_saving_graph" проверяет это, а также и информацию о кол-ве узлов, меток и тд

2021-09-08 12:48 UTC, vdshk requested changes
В целом всё супер. Исправьте одно замечание по поводу документации и будет зачтено

2021-09-08 12:48 UTC, vdshk commented on project/__main__.py
> +    Returns
Между смысловыми объектами документации должна быть одна пустая строка
```suggestion
    Main function, console application runs there

    Returns
```

2021-09-08 12:48 UTC, vdshk commented on project/__main__.py
> +    Returns
И так везде

2021-09-08 13:15 UTC, vladislav-miroshnikov commented on project/__main__.py
> +    Returns
Поправлено

2021-09-08 13:21 UTC, vdshk approved these changes
Молодец :+1:

> Советую, чтобы не сохранять все исправления в истории, сделать `Squash and merge`

2021-09-08 13:22 UTC, merged