Task6 wcnf
vladislav-miroshnikov/formal-lang-course pull request #7
Opened 2021-10-17 17:09 UTC by vladislav-miroshnikov

# Задача 6. Преобразование грамматики в ОНФХ
## Задача

- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html) реализовать **функцию** преобразования контекстно-свободной грамматики в ослабленную нормальную форму Хомского.
- [x] Предусмотреть возможность чтения грамматики из файла. Формат файла определяется возможностями pyformalng. Например, можно использовать [эту функцию](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html#pyformlang.cfg.CFG.from_text).
- [x] Добавить необходимые тесты.

2021-10-19 08:56 UTC, vadyushkins requested changes
К сожалению в `pyformlang` строится не совсем ОНФХ, так как там удаляются `epsilon` в телах продукций. Однако на занятии проговаривалось, что в ОНФХ `epsilon` **остаются**.

Также я прошу Вас добавить тестов, отличных от тех, что используются [тут](https://github.com/kznts9v-1lya/formal-lang-course/pull/7) и [тут](https://github.com/bozhnyukAlex/formal-lang-course/pull/6)

- [ ] Стоит добавить тест на то, что получаемая ОНФХ совпадает с той, которую вы ожидаете получить

2021-10-19 08:56 UTC, vdshk commented on project/cfg.py
> +    cnf = cfg.to_normal_form()
Это не ОНФХ. В ОНФХ в теле продукции может встречаться `epsilon`. Если посмотреть реализацию в `pyformlang`, то там в теле продукции не остается `epsilon`.

2021-10-19 08:56 UTC, vdshk commented on tests/test_cfg.py
> +    [("epsilon.txt", "epsilon"), ("grammar.txt", "S"), ("random.txt", "Hello")],
Кажется тут всё-таки должно быть "E"
```suggestion
    [("epsilon.txt", "E"), ("grammar.txt", "S"), ("random.txt", "Hello")],
```

2021-10-19 08:56 UTC, vdshk commented on tests/test_cfg.py
> +    [("epsilon.txt", "epsilon"), ("grammar.txt", "S"), ("random.txt", "Hello")],
И, если вы посмотрите на `cnf.productions`, то получите `set()`, хотя в ОНФХ было бы `E -> epsilon`

2021-10-25 16:26 UTC, vadyushkins requested changes
Есть небольшое замечание. Если объясните, что я не прав или исправите, то будет зачтено на полный балл

2021-10-25 16:26 UTC, vadyushkins commented on project/cfg.py
> +def is_weak_normal_form(csg, cfg):
Либо я что-то не понимаю, либо `csg` стоит заменить на понятное имя

2021-10-25 16:36 UTC, vladislav-miroshnikov commented on project/cfg.py
> +def is_weak_normal_form(csg, cfg):
Ох, это описка. Конечно, здесь имеется в виду КС-грамматика, а не КЗ(следы доклада Максиму Викторовичу про КЗ грамматики). То есть поведение данной функции - принять cfg, то есть оригинальную грамматику, и некую cnf, грамматику, которую мы проверяем на предмет, находятся ли она в ослабленной нормальной форме или нет. Я поправлю и перезапрошу ревью. Спасибо за замечание.

2021-10-25 16:39 UTC, vladislav-miroshnikov commented on project/cfg.py
> +def is_weak_normal_form(csg, cfg):
Хотя конечно, формально КЗ включают КС, но такое именование будет только путать

2021-10-25 17:54 UTC, vladislav-miroshnikov commented on project/cfg.py
> +def is_weak_normal_form(csg, cfg):
Исправил

2021-10-27 15:04 UTC, vadyushkins commented
Кажется `csg` вы не полностью убрали

2021-10-27 19:44 UTC, vladislav-miroshnikov commented
> Кажется `csg` вы не полностью убрали

Исправил

2021-10-28 12:08 UTC, vadyushkins approved these changes
зачтено

2021-10-31 20:20 UTC, merged